version: "3.9"

services:
  app:
    build:
        context: .
        dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true
    environment:
      MYSQL_URL: mysql://guardian:guardian@db:3306/guardian
      JWT_SECRET_KEY: guardian

  db:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: guardian
      MYSQL_DATABASE: guardian
      MYSQL_USER: guardian
      MYSQL_PASSWORD: guardian
    volumes:
      - ./mysql:/var/lib/mysql
