"""Transaction table uuid and status added

Revision ID: 25c7ca3c8315
Revises: fdd75818015f
Create Date: 2024-01-03 13:29:30.883754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c7ca3c8315'
down_revision: Union[str, None] = 'fdd75818015f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('uuid', sa.String(length=255), nullable=False))
    op.add_column('transactions', sa.Column('status', sa.Enum('SUCCESS', 'FAIL', 'PENDING', name='transactionstatusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'uuid')
    # ### end Alembic commands ###
