"""Transaction table relations added

Revision ID: 2e8b2abcc50a
Revises: ce57279538a8
Create Date: 2024-01-03 14:04:12.123264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e8b2abcc50a'
down_revision: Union[str, None] = 'ce57279538a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'card_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'card', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'card_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
