"""Transaction table type added

Revision ID: d6679a935536
Revises: 2e8b2abcc50a
Create Date: 2024-01-03 15:37:40.893764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6679a935536'
down_revision: Union[str, None] = '2e8b2abcc50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAW', name='transactiontypeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###
